services:
  email_server:
    image: diegoneves/email-server:latest
    container_name: email_server
    ports:
      - "8081:8081"

  racha-pedido-app:
    image: diegoneves/racha-pedido:beta
    container_name: racha-pedido
    ports:
      - "8080:8080"
    depends_on:
      - email_server
    environment:
      - EMAIL_HOST=email_server
      - EMAIL_PORT=8081
      - KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9094
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
