server:
  port: 8080

spring:
  api:
    url:
      send-email: http://${EMAIL_HOST}:${EMAIL_PORT}/sendmail

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
    springframework:
     security: DEBUG
