server:
  port: 8080

spring:
  api:
    url:
      send-email: http://${EMAIL_HOST}:${EMAIL_PORT}/sendmail

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
    springframework:
     security: DEBUG
