server:
  port: 8080

spring:
  api:
    url:
      send-email: http://${EMAIL_HOST}:${EMAIL_PORT}/sendmail

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: racha-pedido-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      send_email: racha-pedido.send_email


springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
    springframework:
     security: DEBUG
